[site]
name = "The Robotics Book"
style = "book"
icon = "media/favicon.ico"

[menu]
names = ["Home", "About", "Authors", "Articles", "License", "Contact"]
links = ["/", "/about", "/authors", "/articles", "/license", "/contact"]

[media]
include = []

[analytics]
tag = "analytics-tag.html"
